export const CARS_DATA = [
  {
    year: 2010,
    favorites: 20,
    make: "Mercedes-Benz",
    model: "SLS AMG",
    location: {
      city: "London",
      country: "United Kingdom",
    },
    price: "US$200,000",
    time_left: "6 days",
    image: "/images/mercedes.webp",
  },
  {
    year: 2018,
    favorites: 20,
    make: "BMW",
    model: "M4 GTS",
    location: {
      city: "Munich",
      country: "Germany",
    },
    price: "€120,000",
    time_left: "6 days",
    image: "/images/bmw.webp",
  },
  {
    year: 2020,
    favorites: 20,
    make: "McLaren",
    model: "720S",
    location: {
      city: "California",
      country: "USA",
    },
    price: "US$210,000",
    time_left: "7 days",
    image: "/images/mclaren.webp",
  },
  {
    year: 2015,
    favorites: 20,
    make: "Porsche",
    model: "911 Turbo S",
    location: {
      city: "Dubai",
      country: "UAE",
    },
    price: "20,000 AED",
    time_left: "7 days",
    image: "/images/porsche.webp",
  },
  {
    year: 2016,
    favorites: 20,
    make: "Aston Martin",
    model: "Vantage GT12",
    location: {
      city: "London",
      country: "United Kingdom",
    },
    image: "/images/astonMartin1.webp",
    price: "£95,500",
    time_left: "7 days",
  },
  {
    year: 1995,
    favorites: 20,
    make: "Land Rover",
    model: "Defender 90",
    location: {
      city: "New York",
      country: "USA",
    },
    price: "US$85,500",
    time_left: "7 days",
    image: "/images/landRover.webp",
  },
  {
    year: 2019,
    favorites: 20,
    make: "Range Rover",
    model: "Autobiography",
    location: {
      city: "Dubai",
      country: "UAE",
    },
    price: "Not listed",
    time_left: "Not listed",
    image: "/images/rangeRover.webp",
  },
  {
    year: 1998,
    favorites: 20,
    make: "Porsche",
    model: "911 Carrera",
    location: {
      city: "Dubai",
      country: "UAE",
    },
    price: "Not listed",
    time_left: "Not listed",
    image: "/images/porsche.webp",
  },
  {
    year: 1955,
    favorites: 20,
    make: "AstonMartin2",
    model: "XK140",
    location: {
      city: "London",
      country: "United Kingdom",
    },
    price: "Not listed",
    time_left: "Not listed",
    image: "/images/astonMartin2.webp",
  },
];
